  CREATE TABLE TELEMETRY (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DEVICE_ID INT NOT NULL,
    MEASUREMENT INT NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX idx_telemetry_device_id_creation_date ON TELEMETRY (DEVICE_ID, CREATION_DATE)